//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KateRecipesV2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Recipe
    {   [Key]
        public int Id { get; set; }
        [DisplayName("Nazwa")]
        [Required]
        public string Name { get; set; }
        [DisplayName("Krótki opis")]
        [Required]
        public string ShortDescryption { get; set; }
        [DisplayName("Sk³adniki")]
        [Required]
        public string Components { get; set; }

        [DisplayName("Wykonanie")]
        [Required]
        public string Implementations { get; set; }

        [DisplayName("Kategoria")]
        [Required]
        public string Category { get; set; }
        public byte[] ImageData { get; set; }
        public string ImageMimeType { get; set; }
     
        
    }
}
